# Generated by Django 4.0.3 on 2023-11-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_operating_hours_doctor_friday_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='departments',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.department'),
        ),
    ]
