# Generated by Django 4.0.3 on 2023-11-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_departments_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctor.department'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='non_insurance_services',
        ),
        migrations.AddField(
            model_name='doctor',
            name='non_insurance_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.noninsuranceservice'),
        ),
    ]
