# Generated by Django 4.0.3 on 2023-11-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_department_doctor_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='non_insurance_services',
        ),
        migrations.AddField(
            model_name='doctor',
            name='non_insurance_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='doctor.noninsuranceservice'),
        ),
    ]
