# Generated by Django 4.0.3 on 2023-11-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_doctor_friday_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentrequest',
            old_name='expiration_datetime',
            new_name='expiration_time',
        ),
        migrations.RenameField(
            model_name='appointmentrequest',
            old_name='request_datetime',
            new_name='requested_time',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='is_accepted',
        ),
    ]
