# Generated by Django 4.0.3 on 2023-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_rename_expiration_datetime_appointmentrequest_expiration_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentrequest',
            old_name='expiration_time',
            new_name='expiration_datetime',
        ),
        migrations.RenameField(
            model_name='appointmentrequest',
            old_name='requested_time',
            new_name='request_datetime',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
