# Generated by Django 4.0.3 on 2023-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_rename_expiration_time_appointmentrequest_expiration_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='is_accepted',
        ),
    ]
