# Generated by Django 4.0.3 on 2023-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_remove_appointmentrequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
