# Generated by Django 4.0.3 on 2023-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctor_lunch_end_doctor_lunch_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
